name: GENERATE APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java 15
        uses: actions/setup-java@v3
        with:
          java-version: 15
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease \
            --build-cache \
            --parallel \
            --daemon \
            --warning-mode all \
            --refresh-dependencies  # 清理依赖缓存

      - name: Prepare APK files
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find . -type f -name "*.apk" -print0 | xargs -0 -I {} mv {} ${{ github.workspace }}/apk/

      - name: Upload APK to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ${{ github.workspace }}/apk/*
          retention-days: 1  # 保留1天
